package pojos;
// Generated 2018.12.23. 13:36:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name="author"
    ,catalog="booklibrary"
)
public class Author  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Book> books = new HashSet<Book>(0);

    public Author() {
    }

    public Author(String name, Set<Book> books) {
       this.name = name;
       this.books = books;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="author")
    public Set<Book> getBooks() {
        return this.books;
    }

    @Override
    public String toString() {
        return  name;
    }
    
    public void setBooks(Set<Book> books) {
        this.books = books;
    }




}


