package pojos;
// Generated 2018.12.23. 13:36:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client",
         catalog = "booklibrary"
)
public class Client implements java.io.Serializable {

    private Integer id;
    private String name;
    private String email;
    private Set<Book> books = new HashSet<Book>(0);

    public Client() {
    }

    public Client(String name, String email, Set<Book> books) {
        this.name = name;
        this.email = email;
        this.books = books;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "email", length = 45)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="client")
    public Set<Book> getBooks() {
        return this.books;
    }


    public void setBooks(Set<Book> books) {
        this.books = books;
    }

    @Override
    public String toString() {
        return  name;
    }

}
